[Feat/#9] 예약 요청 뷰 구현
NOW-SOPT-CDSP-TEAM-WEB2/Client pull request #19
Opened 2024-05-19 14:37 UTC by Ivoryeee

### ✨ 해당 이슈 번호 ✨

closes #9

### todo 

- [ ] 예약 요청 페이지 내 컴포넌트 구현
- [ ] util 함수 구현 

## 📌 폴더 구조

```
|-- 📁 pages/postResrvation
|	 |
|        |-- 📁 components
|	 |		|-- 📁 header //예약 요청 페이지 내 헤더 구현
|	 |		|      |-- PostReservationHeader.tsx
|	 |		|
|	 |		|- 📁 left_side // 예약 요청 페이지 좌측 컴포넌트
|	 |		|      |-- WrapLeftComponents.tsx // 좌측 컴포넌트들 모두 포함됨 
|	 |		|      |-- CardNotice.tsx // 좌측 최상단 카드
|	 |		|      |-- ReserveInfo.tsx // 예약 정보
|	 |		|      |-- SelectPayment.tsx // 결제 방식 선택
|	 |		|      |-- PaymentWay.tsx // 결제 수단
|	 |		|     |-- SendingMessage.tsx // 호스트에게 메시지 보내기
|	 |		|      |-- RefundPolicy.tsx // 환불 정책
|	 |		|      |-- PostButton.tsx // 예약 요청 버튼
|	 |		|
|	 |		|-- 📁 right-side
|	 |		|      - InfoReservationCard.tsx // 숙소 정보 제외한 정보가 담김
|	 |		|      - AccomodationCard.tsx // 우측 컴포넌트 중 숙소 정보 담김
|	 |
|        |-- 📁 constants
|	 |		|      |-- apiTestText.ts //api Test 위한 상수 
|	 |		|      |-- postReservationText.ts // 기타 문자 상수 
|        |-- 📁 utils
|	 |		|      |--extractMonthAndDay.ts
|	 |		|      |--getDiffrenceDate.ts
|	 |		|      |--getPaymentDay.ts
|	 |		|      |--getPaymentDay.ts
|	 |		|      |--getRefundDate.ts
|	 |
|	 |--PostReservationPage.tsx

```

## 📌util 함수 

##📍extractMonthAndDay : YYYY-MM-DD 형식의 string에서 월, 일을 반환하는 함수
```
export function extractMonthAndDay(dateStr: string): { month: string; day: string } | string {
  const dateParts: [string, string, string] = dateStr.split('-') as [string, string, string];

  if (dateParts.length !== 3) {
    return 'YYYY-MM-DD 형식의 데이터로 입력해 주세요';
  }

  const month: string = dateParts[1];
  const day: string = dateParts[2];

  return { month, day };
}
```

##📍getDifferenceDate: 숙박 기간을 num으로 반환
```
export function getDifferenceDate(dateString1, dateString2): number {
  const date1: Date = new Date(dateString1);
  const date2: Date = new Date(dateString2);

  const diffInMilliseconds: number = Math.abs(date2.getTime() - date1.getTime());

  const millisecondsInOneDay: number = 1000 * 60 * 60 * 24;
  const diffInDays: number = Math.floor(diffInMilliseconds / millisecondsInOneDay);

  return diffInDays;
}

```

##📍getPaymentDay: selectPayment에서 나중에 결제하기 선택 시 차액이 지불되는 날 반환
```
export function getDateBeforeDays(inputDate: string): string {
  const date = new Date(inputDate);
  date.setDate(date.getDate() - 10);

  const year = date.getFullYear();
  const month = (date.getMonth() + 1).toString().padStart(2, '0');
  const day = date.getDate().toString().padStart(2, '0');

  const paymentPeriod = `${year}년 ${month}월 ${day}일`;

  return paymentPeriod;
}
```

##📍getPaymentDay: 수수료, 총 금액 등 금액을 계산
```
export function getPrice(price, difference): number {
  const detailPrice = price * difference; /// 일자별 금액*숙박일
  const commissionFee = Math.floor(detailPrice * 0.142); /// accomodationCard에 나타나는 에어비앤비 수수료
  const totalPrice = detailPrice + commissionFee; /// 총 지불 금액

  const departPrcie = Math.floor(totalPrice * 0.2); /// selectPayment에 나타나는 결제 방식 선택에 따른 납부 수수료
  const otherPrice = totalPrice - departPrcie;  /// 총 지불 금액에서 selectPayment에서 이미 지불된 금액을 제외한 현재 지불될 금액

  return { detailPrice, commissionFee, totalPrice, departPrcie, otherPrice };
}

```

##📍getRefundDate: 'mm월 dd일' 형식의 string을 input 으로 받아와 'mm월 dd일' 형식의 환불 마감일 반환
```
export function getRefundDate(inputDate: string): string {
  const month = inputDate.split('월 ')[0];
  const parsedMonth = parseInt(month);
  const day = inputDate.split(' ')[1];
  const parsedDay = parseInt(day);

  const date = new Date();
  date.setMonth(parsedMonth - 1); // 월은 0부터 시작하므로 1을 빼줍니다.
  date.setDate(parsedDay - 1); // 하루 전 날짜로 설정합니다.

  const monthString = (date.getMonth() + 1).toString().padStart(2, '0');
  const dayString = date.getDate().toString().padStart(2, '0');

  return `${monthString}월 ${dayString}일`;
}

```

## 📌 내가 알게 된 부분

- 우측 상단에 숙소 상세 정보를 표시하는 AccomodationCard.tsx 컴포넌트에서 슈퍼호스트인 경우에만 MedalFillBlackIcon과 슈퍼호스트 텍스트가 나타나도록 styled-component 설정을 입력하던 중 props 에러가 나타났다.
```
const MyComponent = (props) => (
/...../
    {props.isSuperHost && (
      <>
        <IconWrapper isSuperHost={props.isSuperHost}>
          <MedalFillBlackIcon />
        </IconWrapper>
        슈퍼호스트
      </>
/...../
);

const IconWrapper = styled.span`
  position: relative;
  display: inline-block;
  ${props => props.isSuperHost && `
    padding-left: 0.6rem;
  `}
`;

```
라고 작성했더니
React does not recognize the `isSuperHost` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `issuperhost` instead. If you accidentally passed it from a parent component, remove it from the DOM element 
라는 에러가 떴다...이는 React에서 합법적인 DOM 속성으로 인식되지 않는 props로 DOM 요소를 렌더링 할 때 발생하는 unknown-prop 경고다. 

에러가 난 부분을 수정하기 위해 styled-components에서 제공하는 기능인 Transient props을 사용했다!
 이는 prefix로 $를 붙여 styled-components에서는 props로 사용되지만 실제 React Dom 속성으로 전달되는 것을 방지하는 기능을 한다. 

```
const IconWrapper = styled.span<{ $issuperHost: boolean }>`
  position: relative;
  top: 0.25rem;
  display: inline-block;
  padding-left: ${(props) => (props.$issuperHost ? '0.6rem' : '0')};
`;
```

참고
https://gist.github.com/meddokss/009cdb5192e487654c0d90cd8f692214

-

## 📌 질문할 부분 
- 좌측 컴포넌트와 우측 컴포넌트 모두 숙박일을 계산해야 해 가장 상위 페이지인 PostReservationPage에서 DifferenceIndays 함수를 사용해 props로 숙박일을 넘겨 주었습니다! 상단 페이지에서는 컴포넌트들만 import 하고 싶었는데 더 좋은 방법이 떠오르지 않아 이와 같이 구현했습니다. 더 좋은 방법이 있을지 여러분과 이야기 나눠 보고 싶습니다!

```
const PostReservationPage = () => {
  const [checkInDate, setCheckInDate] = useState<string>('');

  const [checkOutDate, setCheckOutDate] = useState<string>('');
  const [daysDifference, setDaysDifference] = useState<number>('');
  const [paymentDate, setPaymentDate] = useState<string>('');

  const EditDate = () => {
    DifferenceIndays(API_Test.checkInDate, API_Test.checkOutDate);
    const { month: checkInmonth, day: checkInday } = extractMonthAndDay(API_Test.checkInDate);
    setCheckInDate(checkInmonth + '월 ' + checkInday + '일');
    const { day: checkOutday } = extractMonthAndDay(API_Test.checkOutDate);
    setCheckOutDate(checkOutday + '일');
    const paymentPeriod = getDateBeforeDays(API_Test.checkInDate);
    setPaymentDate(paymentPeriod);
  };

  const DifferenceIndays = (dateString1, dateString2) => {
    const daysDifference = getDifferenceDate(dateString1, dateString2);
    setDaysDifference(daysDifference);
  };

  useEffect(() => {
    EditDate();
  }, []);

  return (
    /.../
);
`

## 📌스크린샷

![image](https://github.com/NOW-SOPT-CDSP-TEAM-WEB2/Client/assets/105477246/5aa485a6-2cd4-4b78-917b-738858a55ce3)

2024-05-21 09:33 UTC, se0jinYoon requested changes
야무지게 잘 해놨네 !!!! 몇가지 수정사항 있어서 어푸 아직 안 남겨둘게요 ! 확인해보고 수정하고, 답글 달아주세요옵! 
근데 상아 파일분리랑 상수 분리 너무 잘해뒀다 !! 그리고 api 미리 연결 테스트 해둔 것도 너무 좋아요오 ~ 
뭐가 엄청 많았는데 .. 유틸도 잘 만들어주고 아주 조아요옵

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/PostReservationPage.tsx
> +  };
음 이 부분을 커스텀 훅으로 빼서 구현해보면 좋을 것 같아요 !!
위의 상태값들이 전부 날짜를 추출(?)하기 위해서 사용되는 것 같은데, 그런 경우 (로직(유틸)과 관련된 함수들을 다루기 위한 state값들의 경우)는 커스텀훅 내부에서 다음과 같은 상태들을 정의하고, 커스텀훅 내부에서 유틸함수를 불러와서 사용한 후, 원하는 값들을 리턴하는 형식으로 사용해보면 좋을 것 같슴니당

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/PostReservationPage.tsx
> +
여기 의존성에 아무것도 안 들어가도 되나요 ? 

useEffect의 의존성 값으로는 내부에서 사용되는 모든 값을 넣어주는게 좋답니다!
다만 객체값이나 함수(useState의 setter함수 포함)을 넣어줄 경우에는 원하지 않는 리렌더링이 발생할 수 있기 때문에 (참조값의 경우에는 리렌더링될 때마다 메모리 주소가 바뀌기 때문에 동일한 함수, 동일한 객체값이여도 다른 값으로 판단하게 됩니다) 
객체내에서 사용하는 특정 값을 의존성에 넣어주는게 좋아요 (예를들어 API_Test.checkInDate 이런식으로!)
함수의 경우에는 저는 의존성에 잘 넣지 않는 편이에요. 꼭 넣어야하는 경우라면 useCallback이나 useMemo와 같은 것을 이용해서 해당 함수가 변하지 않았음을 보장한 후에 넣어주곤합니다!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/PostReservationPage.tsx
> +  }
우리 반응형 안하니까 여기 부분은 빼주기!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/CardNotice.tsx
> +const CardNotice = (props: Props) => {
옹 여기 interface가 아닌 type을 쓴 이유가 있나요 ? 

그리고 저희 prop 타입 네이밍 컨벤션!
```suggestion
interface CardNoticeProps = {
  hostName: string;
};
const CardNotice = (props: CardNoticeProps) => {
const {hostName} = props;
```
<img width="817" alt="스크린샷 2024-05-21 오후 6 13 01" src="https://github.com/NOW-SOPT-CDSP-TEAM-WEB2/Client/assets/109661444/2401d7c0-07c5-448d-9d1d-6d153fd17189">

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/CardNotice.tsx
> +            {props.hostName}
위와같이 받아오는 걸 수정하면 hostName만 써줄 수 있겠죠 ?

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/PostButton.tsx
> +const PostButton = (props: ButtonProps) => {
여기도 컨벤션 맞춰주기!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/PostButton.tsx
> +    </>
여기 `<> </>`로 한 번 더 감싸준 이유가 있나요 ?

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/RefundPolicy.tsx
> +const RefundPolicy = (props: Props) => {
여기도 컨벤션!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/RefundPolicy.tsx
> +          <TextArea3Normal>{RefundPolicyContent.contentDetail_normal3}</TextArea3Normal>
크 상아 상수 분리 진짜 잘한다 나 귀찮아서 때려박았는데 ... 반성하고 배워갑니다잉

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/ReserveInfo.tsx
> +const ReserveInfo = (props: Props) => {
여기도!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/ReserveInfo.tsx
> +              {' '}
옹 이게 왜생겼지? 지워줍시당!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/SelectPayment.tsx
> +    <>
옹 모든 컴포넌트가 이렇게 감싸져있는데 왜일까요 ?
`<> </>` 제외하고도 SelectPaymentWrapper가 최상단에 감싸고 있어서 괜찮을 거 같은데!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/SendingMessage.tsx
> +                {' '}
여기도 지워주기!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/SendingMessage.tsx
> +                {SendingMessageContent.hostInfo} {props.yearsOfHosting}년{' '}
어머 여기두

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/SendingMessage.tsx
> +const SendingMessage = (props: Props) => {
여기도 컨벤션 맞추기!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/left_side/WrapLeftComponents.tsx
> +const WrapComponents = (props: Props) => {
여기두!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/right_side/AccomodationCard.tsx
> +const AccomodationInfoCard = (props: Props) => {
여기도 컨벤션!

2024-05-21 09:33 UTC, se0jinYoon commented on src/pages/postReservation/components/right_side/InfoReservationCard.tsx
> +const InfoReservationCard = (props: Props) => {
여기도 컨벤션~

2024-05-21 14:44 UTC, rtttr1 approved these changes
LGTM!! 어마어마한 상수양과 util함수가 있었는데 다 꼼꼼하게 잘 마무리하셨네요!!!! 원래도 엄청 깔끔했을 텐데 서진이가 한번 코리해주고 간거 반영해서 그런가 딱히 리뷰를 할게 없는 깔끔한 코드 잘 보고갑니다 API도 화이팅해봐요!!!

2024-05-21 14:44 UTC, rtttr1 commented on src/pages/postReservation/PostReservationPage.tsx
> +  };
p5) 커스텀훅은 위대해서 빼보면 상아님도 감탄할거에요 본인코드의 깔끔함에.. 마치 저처럼..

2024-05-21 14:44 UTC, rtttr1 commented on src/pages/postReservation/PostReservationPage.tsx
> +  grid-template-columns: repeat(2, 1fr);
p5) 혹시 1fr 쓴 부분에서 style lint 에러 안났나요? 저는 에러가 나던데 일단 넘기긴했는데 이유를 못찾았습니다ㅠ

2024-05-21 14:44 UTC, rtttr1 commented on src/pages/postReservation/components/left_side/WrapLeftComponents.tsx
> +const WrapComponents = (props: Props) => {
p5) 저희 props 컨벤션처럼 const {checkInDate, checkOutDate, daysDifferece, paymentData} = props 로 props값들 받아와서 사용해도 밑에 jsx 부분 코드가 조금 더 깔끔해질수도 있을것 같아요!

2024-05-21 14:44 UTC, rtttr1 commented on src/pages/postReservation/constatnts/apiTestText.ts
> +};
p5) 크.. api 테스트 상수까지.. 대박!

2024-05-22 12:54 UTC, jeeminyi approved these changes
util 함수 정말 잘 짜줘서 캘린더 커스텀할 때 유용하게 참고할 수 있을 것 같습니다! 보면서 코드를 컴팩트하게 정말 잘 짰다는 생각이 들었어요..,,, 멋있읍니다 더 뜯어보면서 많이 배우도록 하겠슴다!!

2024-05-22 12:54 UTC, jeeminyi commented on src/pages/postReservation/constatnts/postResevationText.ts
> +};
와아 이런 식으로 텍스트를 상수 데이터로 빼서 해줄 생각은 정말 못했어요,, 하드코딩 해놓은 제 코드 보면서 가독성이 너무 떨어지고 구조를 못 잡아서 이해하기 너무 어려운 점이 고민이었는데 이런 식으로 해줄 수도 잇군요,, 많이 배우고 갑니다..리팩 때 적용해봐야겠어요

2024-05-22 12:54 UTC, jeeminyi commented on src/pages/postReservation/hooks/extractDate.tsx
> +  }, [checkOutDate]);
날짜 커스텀 훅도 너무 잘 정리해놓으셔서 캘린더 커스텀할 때 많이 참고해야겠어요,, 오늘도 배우고 갑니다,,,sooososososo LGTM

2024-05-22 12:54 UTC, jeeminyi commented on src/pages/postReservation/utils/extractMonthAndDay.ts
> +  }
오 이런 식으로 디테일하게 처리해줄 수도 있군요..! 뜯어보면서 많이 배웁니다,,

2024-05-23 11:45 UTC, se0jinYoon approved these changes

2024-05-23 11:47 UTC, merged

2024-09-14 13:12 UTC, Ivoryeee commented on src/pages/postReservation/components/left_side/CardNotice.tsx
> +            {props.hostName}
구조분해 할당을 하고 나니 정말 더 간단하게 쓸 수 있네요!! +0+ props가 많은 컴포넌트에서 props.xxxx로 인자를 작성하다 보니 헷갈리기도 했는데, 구조 분해 할당의 중요성을 다시끔 깨우치고 갑니다!!

2024-09-14 13:12 UTC, Ivoryeee commented on src/pages/postReservation/components/left_side/PostButton.tsx
> +    </>
의도는 DOM 트리를 더 간결하게 만들기 위해서 Wrapper의 div 대신 Fragments (<></>)를 사용하려 했던 건데... 생각해 보니 요기에서는 Wrappper이 필요가 없겠네요...............! 놓치고 있던 부분인데 짚어주셔서 감사드립니다 바로 수정할게욧!

2024-09-14 13:12 UTC, Ivoryeee commented on src/pages/postReservation/components/left_side/SelectPayment.tsx
> +    <>
이번에 보니 제가 개발할 때 항상 <></> fragment로 감싸고 있었더라구요...  wrapper에 style이 부여되지 않는다면 <div> 대신 <></>로 감싸서 추가 DOM 노드의 생성을 지양하면 좋을 듯 한데, 이번 퍼블리싱에서는 대부분 최상단 wrapper에 스타일이 추가돼 있어서 <></>로 바꾸었습니다!

2024-09-14 13:12 UTC, Ivoryeee commented on src/pages/postReservation/components/left_side/CardNotice.tsx
> +const CardNotice = (props: Props) => {
으악 제 실수입니다 ㅜ_ㅜ 바로 수정 들어가겠슴니다!!

2024-09-14 13:12 UTC, Ivoryeee commented on src/pages/postReservation/PostReservationPage.tsx
> +  grid-template-columns: repeat(2, 1fr);
저도 stylelint 에러 났어요! 허용되는 단위값으로 fr이 추가되어 있지 않아서 그러는데 제 커밋 내역 중에 추가해 뒀습니다!! 머지하면 해결될 거예욥!

2024-09-14 13:12 UTC, Ivoryeee commented on src/pages/postReservation/PostReservationPage.tsx
> +  };
안 그래도 이 부분 코드가 유독 간결하지 않은 것 같아 고민이 많았는데 서진님이 해결 방법을 너무 잘 짚어주셨네요...! 정말 규홍님 말씀하신 것처럼 코드가 이렇게 깔끔해질 수 있구나 감탄했습니다... 

```

export const useExtractDate = (checkInDate, checkOutDate) => {
  const [formattedCheckInDate, setFormattedCheckInDate] = useState('');
  const [formattedCheckOutDate, setFormattedCheckOutDate] = useState('');
  const [daysDifference, setDaysDifference] = useState(0);
  const [paymentDate, setPaymentDate] = useState('');

  const formatCheckInDate = useCallback(() => {
    const { month, day } = extractMonthAndDay(checkInDate);
    return `${month}월 ${day}일`;
  }, [checkInDate]);

  const formatCheckOutDate = useCallback(() => {
    const { day } = extractMonthAndDay(checkOutDate);
    return `${day}일`;
  }, [checkOutDate]);

  const calculateDaysDifference = useCallback(() => {
    return getDifferenceDate(checkInDate, checkOutDate);
  }, [checkInDate, checkOutDate]);

  const calculatePaymentDate = useCallback(() => {
    return getDateBeforeDays(checkInDate);
  }, [checkInDate]);

  useEffect(() => {
    if (checkInDate && checkOutDate) {
      setFormattedCheckInDate(formatCheckInDate());
      setFormattedCheckOutDate(formatCheckOutDate());
      setDaysDifference(calculateDaysDifference());
      setPaymentDate(calculatePaymentDate());
    }
  }, [checkInDate, checkOutDate, formatCheckInDate, formatCheckOutDate, calculateDaysDifference, calculatePaymentDate]);

  return {
    formattedCheckInDate,
    formattedCheckOutDate,
    daysDifference,
    paymentDate,
  };
};
```
이렇게 커스텀 훅으로 빼주었고, 덕분에 PostResevationPage는
```
const PostReservationPage = () => {
  const { formattedCheckInDate, formattedCheckOutDate, daysDifference, paymentDate } = useExtractDate(
    API_Test.checkInDate,
    API_Test.checkOutDate
  );

  return (
``` 
짠 이렇게 간결해졌어요!!!! 넘 최고네요... 커스텀훅 앞으로 잘 활용해 봐야겠어요

2024-09-14 13:12 UTC, Ivoryeee commented on src/pages/postReservation/PostReservationPage.tsx
> +
그저 렌더링을 위해서만 useEffect 내에 함수를 추가해 주고, 의존성 배열에 값을 할당할 생각도 못했던 것 같아요.. 정말 부족했던 부분인데 잘 짚어주신 덕에 이번에 useEffect의 사용 방법에 대해 다시 고민해 보고 갑니다! 

```
//extractDate.tsx

export const useExtractDate = (checkInDate, checkOutDate) => {
    /.../
  const formatCheckInDate = useCallback(() => {
    const { month, day } = extractMonthAndDay(checkInDate);
    return `${month}월 ${day}일`;
  }, [checkInDate]);
    /.../
 useEffect(() => {
    if (checkInDate && checkOutDate) {
      setFormattedCheckInDate(formatCheckInDate());
      setFormattedCheckOutDate(formatCheckOutDate());
      setDaysDifference(calculateDaysDifference());
      setPaymentDate(calculatePaymentDate());
    }
  }, [checkInDate, checkOutDate, formatCheckInDate, formatCheckOutDate, calculateDaysDifference, calculatePaymentDate]);
```
커스텀훅 extractDate.tsx에서 useEffect 부분을 요렇게 수정하여 작성했습니다!

2024-09-14 13:12 UTC, Ivoryeee commented on src/pages/postReservation/components/left_side/WrapLeftComponents.tsx
> +const WrapComponents = (props: Props) => {
역시 규홍님 꼼꼼함 최고... 👍🏻 바아로 수정하겠습니다!

2024-09-14 13:12 UTC, Ivoryeee commented on src/pages/postReservation/constatnts/postResevationText.ts
> +};
저도 원래 텍스트로 바꿔 놨다가 조금 더 깔끔하게 바꿀 수 있을까 해서 바꿔봤어요 ㅎㅎ 훨씬 코드가 깔끔해지더라구요!! 텍스트 데이터 분리... 강추합니다! 👍🏻