[Feat/#20] 캐러셀 구
NOW-SOPT-CDSP-TEAM-WEB2/Client pull request #24
Opened 2024-05-21 09:09 UTC by Ivoryeee

### ✨ 해당 이슈 번호 ✨

closes #20 

### todo 

- [ ] 캐러셀 컴포넌트 구현
- [ ] navigation (1) 캐러셀 hover 시 나타나게 커스텀
- [ ] navigation (2) 첫 슬라이드와 마지막 슬라이드에서는 각각 다음 페이지 버튼, 이전 페이지 버튼만 나타나게 커스텀 
- [ ] Pagination Bullet Dynamic  (1) 슬라이드 위치에 따라 Bullet의 크기가 달라지도록 커스텀

## 📌 폴더 구조

```
|-- 📁 component/common/carousel
|	 |
|        |-- 📁 carouselComponents // 캐러샐 관련 컴포넌트
|	 |		|
|	 |		|-- 📁 css // 캐러샐 관련 css 파일
|	 |		|      |-- slick-theme.css
|	 |		|      |-- slick.css
|	 |		|- Carousel.tsx //Carousel 기능 구현
|	 |		|- CustomArrow.tsx //Carousel navigation 커스텀
|	 |		|
|        |-- 📁 components
|	 |		|-- CarouselText.tsx 캐러셀 컨포넌트 내 숙소 정보 
|	 |		|-- HeartComponent.tsx //위시리스트 좋아요 
|	 |		|-- SuperHostCard.tsx //슈퍼호스트 카드
|	 |	
|	 | 📁 constants
|	 |	| - apiTest.tsx // api Test 위한 상수 데이터
|	 |		
|	 |--CarouselWrapperComponent.tsx  // 캐러셀 관련 부모 컴포넌트

```

## 📌 캐러셀 라이브러리 도입기 

 프로젝트에 캐러셀을 도입해 본 게 처음이라 관련 라이브러리를 찾아보며 아티클로 정리해 뒀습니다 
https://ivoryeee.tistory.com/23

## 📌 CustomArrow custom

```
///CustomArrows.tsx

import { LeftCircleBtn, RightCircleBtn } from '../../../../assets/svgs';

type ArrowProps = {
  className?: string;
  style?: React.CSSProperties;
  onClick?: React.MouseEventHandler<HTMLDivElement>;
};

export const NextArrow: React.FC<ArrowProps> = ({ className, style, onClick }) => (
  <div
    className={`${className}`}
    style={{
      ...style,
    }}
    onClick={onClick}>
    <RightCircleBtn />
  </div>
);

export const PrevArrow: React.FC<ArrowProps> = ({ className, style, onClick }) => (
  <div
    className={`${className}`}
    style={{
      ...style,
    }}
    onClick={onClick}>
    <LeftCircleBtn />
  </div>
);

// Carousel.tsx

import { NextArrow, PrevArrow } from './CustonArrows';

const Carousel: React.FC<Props> = (props: Props) => {
     /.../
  const settings = {
    dots: true,
    infinite: false,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    nextArrow: <StyledNextArrow /> ;  //우측 네비게이션 지정
    prevArrow: <StyledPrevArrow /> ;  //좌측 네비게이션 지정
```

Arrow 커스텀은 React-slick 공식 문서에 잘 나와 있어서 아티클을 참고하였습니다!
https://react-slick.neostack.com/docs/example/custom-arrows

## 📌navigation (1) 캐러셀 hover 시 나타나게 커스텀

```
//Carousel.tsx

const Carousel: React.FC<Props> = (props: Props) => {
 const [isHovered, setIsHovered] = useState(false);
 
   const setting ={
     /.../
    nextArrow: isHovered ? <StyledNextArrow /> : null,
    prevArrow: isHovered ? <StyledPrevArrow /> : null,
    };
     /.../

  return (
    <>
       /* 캐러셀 영역 hover 추가  */
      <div
        className="carousel-container"
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}>
        <Slider {...settings} onMouseEnter={() => setIsHovered(true)} onMouseLeave={() => setIsHovered(false)}>
          {props.roomImageList &&
            props.roomImageList.map((src, index) => <CarouselImg key={index} src={src} alt={`Cat ${index + 1}`} />)}
        </Slider>
      </div>
    </>
  );
};

```

## 📌 navigation (2) 첫 슬라이드와 마지막 슬라이드에서는 각각 다음 페이지 버튼, 이전 페이지 버튼만 나타나게 커스텀 

```
//Carousel.tsx

const Carousel: React.FC<Props> = (props: Props) => {
  const [slideState, setSlideState] = useState({
    activeSlide: 0,
    activeSlide2: 0,
  });

  const settings = {
     /.../
    /* slide의 현재 상태 저장  */
    beforeChange: (current: number, next: number) => setSlideState({ activeSlide: next, activeSlide2: current }),
     /* 현재 슬라이드가 마지막 슬라이드일 경우 nextArrow: null로 지정*/
    nextArrow: isHovered && slideState.activeSlide < 4 ? <StyledNextArrow /> : null,
     /* 현재 슬라이드가 첫번째 슬라이드일 경우 prevArrow: null로 지정*/
    prevArrow: isHovered && slideState.activeSlide > 0 ? <StyledPrevArrow /> : null,
     /.../
```

## 📌 Pagination Bullet Dynamic  (1) 슬라이드 위치에 따라 Bullet의 크기가 달라지도록 커스텀
```
//Carousle.tsx

const Carousel: React.FC<Props> = (props: Props) => {
  const [slideState, setSlideState] = useState({
    activeSlide: 0,
    activeSlide2: 0,
  });

  const settings = {
     /.../
    /* bulletdot 세팅  */
    appendDots: (dots: React.ReactNode) => (
      <div
        style={{
          width: '100%',
          position: 'absolute',
          bottom: '0.9rem',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
        }}>
        /* bulletdot 순회하며 dot의 index가 특정 순서일 때 small-dot 스타일로 나타나게 구현  */
        <ul>
          {React.Children.map(dots, (dot, index) =>
            React.cloneElement(dot as React.ReactElement, {
              className: `${index === slideState.activeSlide ? 'slick-active' : ''} ${
                (index === 0 && slideState.activeSlide === React.Children.count(dots) - 1) ||
                (slideState.activeSlide === 1 && index === 4) ||
                (slideState.activeSlide === 2 && (index === 0 || index === 4)) ||
                (index === React.Children.count(dots) - 1 && slideState.activeSlide === 0) ||
                (slideState.activeSlide === 3 && index === 0)
                  ? 'small-dot'
                  : ''
              }`,
            })
          )}
        </ul>
      </div>
    ),
    dotsClass: 'dots_custom', //slick.css에 스타일 지정
  };
```

## 📌 질문할 부분 
- 없습니다!

## 📌스크린샷

https://github.com/NOW-SOPT-CDSP-TEAM-WEB2/Client/assets/105477246/49989fb3-ec64-4b70-a247-f1ddfd721bbf

2024-05-21 11:02 UTC, se0jinYoon requested changes
너무 깔끔해서 코리할게 없는 이슈 .... 캐러셀 어려웠을텐데 뚝딱뚝딱 너무 잘해와서 리드 우는중이에요 ....... 진짜 너무너무 수고 많았다아 !!!!! 든든상아 최고 ,, 
그 prop 넘기는 컨벤션이랑 하나 달아둔 것만 의견 주세요 !! 감사함니다아 !

2024-05-21 11:02 UTC, se0jinYoon commented on src/components/commons/carousel/carouselComponent/Carousel.tsx
> +    prevArrow: isHovered && slideState.activeSlide > 0 ? <StyledPrevArrow /> : null,
크으 라이브러리 야무지게 잘 써놨네 ... 장하다...

2024-05-21 11:02 UTC, se0jinYoon commented on src/components/commons/carousel/carouselComponent/Carousel.tsx
> +      </div>
오호 이걸 styled-component로 만들어서 넣을 순 없나 ?
여기 dots가 라이브러리에서 제공해주는 값이에요 ?

2024-05-21 12:10 UTC, rtttr1 approved these changes
LGTM~~!! 캐러셀 뚝딱뚝딱 만들어내는거 너무 멋있어요 역시 박상아 최고~~!!

2024-05-21 12:10 UTC, rtttr1 commented on src/components/commons/carousel/carouselComponent/Carousel.tsx
> +const Carousel: React.FC<Props> = (props: Props) => {
p5) React.FC로 함수의 props의 타입을 지정할수 있네요! 타스 왕초보 하나 배워갑니다 핳

2024-05-21 12:10 UTC, rtttr1 commented on src/components/commons/carousel/carouselComponent/css/slick-theme.css
> +}
p5) 으아.. 이 많은 css 다 지정하기 너무 빡셌겠네여 정말 수고 많으셨어요!!

2024-05-21 13:36 UTC, Ivoryeee commented on src/components/commons/carousel/carouselComponent/Carousel.tsx
> +      </div>
완전!!! 가능합니다! css랑 같이 다루다가 정신이 없었는지 깜박 놓쳤네요 역시 최고 리드... 바로 수정하겠슴니다!!

2024-05-22 09:18 UTC, jeeminyi commented on src/components/commons/carousel/carouselComponent/Carousel.tsx
> +const Carousel: React.FC<Props> = (props: Props) => {
오 저도 이번 기회에 react.FC에 대해 처음으로 알아갑니다,, 찾아보니까 props에 기본적으로 children이 들어가있는 함수형 컴포넌트네요! 장단점을 자세히 적어놓은 아티클을 발견해 놓고 갑니다,, 총총
https://shape-coding.tistory.com/entry/TypeScript-ReactFC%EC%97%90-%EC%82%AC%EC%9A%A9%EC%97%90-%EB%8C%80%ED%95%B4-%EC%83%9D%EA%B0%81%ED%95%B4%EB%B3%B4%EA%B8%B0

2024-05-22 09:19 UTC, jeeminyi approved these changes
캐러셀 구현 정말 정말 어려웠을 텐데 깔끔하게 잘 짜신 것 같아요,, 많이 배우고 갑니다 so so LGTM~~~! 아직 이해가 안가는 어려운 부분도 있는데 합세 끝나고도 계속 뜯어보고 상아 괴롭히면서 이해해보려고 노력하겟습니다,, 정말정말 수고 많으셨어요~~!

2024-05-23 11:48 UTC, se0jinYoon approved these changes

2024-05-23 12:11 UTC, merged