Feat/#11/home 페이지 구현
NOW-SOPT-CDSP-TEAM-WEB2/Client pull request #27
Opened 2024-05-21 14:32 UTC by rtttr1

### ✨ 해당 이슈 번호 ✨

closes #11 

### todo 

- [x] 홈 헤더 view 구현
- [x] 홈 헤더 애니메이션 적용
- [x] 홈 메인 Layout view 구현
- [x] 홈 푸터 view 구현

## 📌 내가 알게 된 부분

### 🍀styled-component의 css를 props의 값에 따라서 지정해주고 싶을때 css``을 사용하면 theme을 사용할 수도 있고 쉽게 상황을 나눠서 css를 줄 수 있다!
```typescript
  ${(props) =>
    props.$isScroll
      ? css`
          position: fixed;
          top: 6rem;

          background-color: ${({ theme }) => theme.colors.white};
        `
      : css`
          margin-top: 1.3rem;
        `}
```
위의 코드는 $isScroll값에 따라서 헤더의 위치를 조정해주는 코드입니다. 보시다시피 css``를 사용하면 삼항연산자나 && 와 같은 논리 연산자들을 사용하여 상황을 나누기 편해집니다!

### 🍀 홈 헤더 animation 적용하기

https://github.com/NOW-SOPT-CDSP-TEAM-WEB2/Client/assets/94050324/a7846495-d81a-4709-b504-4d6555a9e538

위의 에어비앤비 홈의 애니메이션을 보면 스크롤시 여행지검색 바가 어디든지바로 바뀌는 듯한 느낌을 준다. 처음엔 어떻게 컴포넌트를 교체하는 애니메이션을 주지? 라는 고민을 하다가 에펠탑든든서진이의 조언을 듣고 찾아보다 답을 찾았다.

1. 여행지검색 바를 translate로 어디든지바 위치로 올리면서 크기를 0으로 만든다.
2. 어디든지 바를 크기 0에서 1로 만든다. 
3. 해당 과정에 delay를 걸어준다.

이와같은 3단계를 거치니 마치 컴포넌트가 바뀌는 듯한 느낌의 애니메이션을 줄 수 있었다.

- 여행지검색바에 적용된 애니메이션
```typescript
  transition: all 0.3s;
  ${(props) =>
    props.$isScroll
      ? css`
          transform: translate(0, -10rem);
          opacity: 0;
          scale: 0;
        `
      : css`
          transform: translate(0, 0);
          opacity: 1;
        `}
```

- 어디든지 바에 적용된 애니메이션
```typescript
transition: all 0.2s;
  ${(props) =>
    props.$isScroll
      ? css`
          /* transform: translate(0, ); */
          scale: 1;
        `
      : css`
          transform: translate(0, 0);
          scale: 0;
        `}
```

### 🍀 사용자정의 훅 사용
-  사용자정의 훅을 사용한 코드를 봤을떄 훨씬 코드가독성이 좋아지는것을 보고 언젠가 사용해보고 만다 라고 다짐했는데 이번에 사용해보게 되었다!
- scroll에 따른 css 애니메이션 변화를 주기 위해 scroll 상태를 추적해야 했고 해당 부분을 사용자 정의 훅으로 만들었다.
```typescript
import { useEffect, useState } from 'react';

const useScrollY = () => {
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll); //clean up
    };
  }, []);

  const handleScroll = () => {
    setScrollY(window.scrollY);
  };
  const isScroll = scrollY > 0;
  return { isScroll };
};

export default useScrollY;

```
- useScrollY 훅은 useState와 useEffect 훅을 사용하여 scroll이 되었는지를 추적하고 scroll되었는지를 boolean 값으로 리턴한다.
- 확실히 사용자정의훅으로 해당 부분을 따로 분리하니 컴포넌트가 훨씬 깔끔해져서 너무 만족했다!
## 📌 질문할 부분 
- 그냥 뭔가 children prop을 사용해보고 싶었는데 못사용해서 혹시 코드 보실때 children props을 사용했더라면 더 깔끔해질 만한 부분이 있다면 슥 알려주시면 고민해보겠습니다!

## 📌스크린샷

2024-05-21 19:04 UTC, se0jinYoon requested changes
애니메이션도 너무 잘 적용해줬고 커스텀훅까지 척척 ,,, 김규홍 잘한다 ,,,,
코드도 너무 깔끔하게 잘 짰고 ! children이용할 수 있을까?라고 질문 남겨줬는데 layout이 크게 공통으로 잡혀있는 부분도 없고,, 이 뷰에서의 핵심은 사실 애니메이션이였기 때문에 지금 로직 유지해서 진행해도 괜찮을 것 같습니다 !!

코드를 많이 생각하고 짠게 보이네요 ,, 너무너무 고생했고 !! 몇가지 코리 남겨둔 부분들만 확인하고 노티주세요 !! 수고했다!!

2024-05-21 19:04 UTC, se0jinYoon commented on src/assets/images/index.ts
> +export { default as spainImg } from './spain.png';
svg를 컴포넌트화해서 export하는 거기 때문에 파일명 시작은 대문자로 해주기!
```suggestion
export { default as CaliforniaImg } from './california.png';
export { default as SpainImg } from './spain.png';
```

2024-05-21 19:04 UTC, se0jinYoon commented on src/assets/svgs/index.tsx
> +export { default as searchMiniWhiteIcon } from './ic_search_mini_white_12.svg?react';
얘도 대문자로!

2024-05-21 19:04 UTC, se0jinYoon commented on src/components/commons/Header.tsx
> +};
우리 prop 네이밍 컨벤션이랑 받아올 때 컨벤션 있슴니다 ! 
```suggestion
interface HomeDefaultHeaderProps = {
  isScroll: boolean;
};
```

![스크린샷 2024-05-22 오전 3 19 01](https://github.com/NOW-SOPT-CDSP-TEAM-WEB2/Client/assets/109661444/d798dcc3-3aec-4aeb-bdcd-af499fa9e5e3)

2024-05-21 19:04 UTC, se0jinYoon commented on src/components/commons/Header.tsx
> +export const HomeDefaultHeader = ({ isScroll }: scroll) => {
```suggestion
export const HomeDefaultHeader = (props: HomeDefaultHeaderProps) => {
const { isScroll } = props;
```

2024-05-21 19:04 UTC, se0jinYoon commented on src/components/commons/Header.tsx
> +      {/* <NavHeaderContent /> */}
주석 지우기~

2024-05-21 19:04 UTC, se0jinYoon commented on src/components/commons/HomeHeaderContent.tsx
> +const HomeHeaderContent = ({ isScroll }: scroll) => {
여기도 prop 컨벤션 맞춰주기~

2024-05-21 19:04 UTC, se0jinYoon commented on src/components/commons/NavHeaderContent.tsx
> +const NavHeaderContent = ({ isScroll }: scroll) => {
여기도 컨벤션!

2024-05-21 19:04 UTC, se0jinYoon commented on src/components/commons/NavHeaderContent.tsx
> +  z-index: 100;
100이나 준 이유가 있나요 ? 
기본이 0이라서 1만 줘도 돼요 ~

2024-05-21 19:04 UTC, se0jinYoon commented on src/components/commons/NavHeaderContent.tsx
> +          /* transform: translate(0, ); */
지우기 주석!

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/hooks/useScrollY.tsx
> +export default useScrollY;
크 커스텀훅 미쳤다 깔꼼하게 너무 잘 구현했다 !!! useEffect 클린업까지 잘 신경써줬네요 굿굿

2024-05-21 19:04 UTC, se0jinYoon commented on src/components/commons/NavHeaderContent.tsx
>  const NavHeaderWrapper = styled.div`
여기서 $isScroll 사용할 때 제네릭으로 $isScroll type 지정해두면 좋을 것 같아요
```suggestion
const NavHeaderWrapper = styled.div<{$isScroll: boolean}>`
```

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/HomePage.tsx
> +  width: 136.6rem;
화면 크기 일부러 고정해서 만들고 있기 때문에 여기 px로 박아주면 됩니다!!

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/HomePage.tsx
> +  width: 136.6rem;
여기두 Px!

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/components/CarouselWrapperList.tsx
> +  /* stylelint-disable-next-line unit-allowed-list */
이거 fr 아마 적용이 안되어서 disable 설정 해둔 것 같은데, 상아가 캐러셀 하면서 stylelint 속성에 fr도 넣어두어서 상아 캐러셀 머지 된 후에는 이 부분 에러 안 뜰거에요 !!

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/components/CarouselWrapperList.tsx
> +const CardWrapper = styled.ul`
시멘틱태그 구웃..

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/components/HomeCategorySearch.tsx
> +  width: 136.6rem;
px!

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/components/HomeFooter.tsx
> +  width: 136.6rem;
px!

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/components/HomeFooter.tsx
> +        })}
오호 여기 Return 안쓰고 사용할 수 있어요 !
```suggestion
        {FooterCarouselItemInfo.map((info) => (
            <FooterCarouselItem key={info.id}>
              <FooterCarouselImg src={info.img} />
              <FooterCarouselInfo>
                <FooterCarouselTitle>{info.title}</FooterCarouselTitle>
                <FooterCarouselRecommend>{info.recommend}</FooterCarouselRecommend>
                <FooterCarouselDescription>{info.description}</FooterCarouselDescription>
                <FooterCarouselPriceWrapper>
                  <FooterCarouselDefaultPrice>{info.defaultPrice}</FooterCarouselDefaultPrice>
                  <FooterCarouselDiscountPrice>{info.discountPrice}</FooterCarouselDiscountPrice>
                  <FooterCarouselDay>{info.day}</FooterCarouselDay>
                </FooterCarouselPriceWrapper>
              </FooterCarouselInfo>
            </FooterCarouselItem>
          ))}
```

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/components/LnbList.tsx
> +  };
여기가 그 문제의 호버,클릭 기타 등등 컴포넌트였구나 ....
분기처리가 엄청나네요 .. 고생했다 ,,

여기 부분을 좀 더 가독성 좋게 하려면 switch-case문을 사용해봐도 좋아요 !
```suggestion
 const handleIconClick = (id: number, identifier: string) => {
  switch (identifier) {
    case 'click':
      const clickTemp = isClickIcon.map((_, index) => (index === id ? true : false));
      setIsClickIcon(clickTemp);
      break;
    case 'mouseOver':
      const hoverTemp = isHoverIcon.map((_, index) => (index === id || isClickIcon[index] ? true : false));
      setIsHoverIcon(hoverTemp);
      break;
    default:
      const defaultTemp = isHoverIcon.map(() => false);
      setIsHoverIcon(defaultTemp);
  }
};
```
이런식으로!

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/components/LnbList.tsx
> +  const [isClickIcon, setIsClickIcon] = useState<boolean[]>([false, false, false, false, false, false, false, false]);
타입 지정 잘했네요 !
이 부분은 조금 더 간결하게 이렇게 바꿔볼 수 있어요!
```suggestion
  const [isHoverIcon, setIsHoverIcon] = useState<boolean[]>(Array(8).fill(false));
const [isClickIcon, setIsClickIcon] = useState<boolean[]>(Array(8).fill(false));
```
es6 문법 많이 사용하기!

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/components/SearchTravel.tsx
> +  const { isScroll } = props;
오호 여긴 컨벤션 잘 지켰네 ! 굿!

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/components/SearchTravel.tsx
> +  }
css 야무지게 잘쓰네..

2024-05-21 19:04 UTC, se0jinYoon commented on src/pages/main/HomePage/constants/index.ts
> +  svgGray: string;
트슈 미쳤다 기록했죠 ?

2024-05-22 02:22 UTC, Ivoryeee approved these changes
LGTM 진짜 고생 많으셨어요!! 애니메이션 부드럽게 잘 적용되는 부분은 정말 감동 그 자체네여 뷰 구현은 물론 규홍님 코드 진짜 잘 짜신다는 걸 다시 한번 느끼고 갑니다!!

2024-05-22 02:22 UTC, Ivoryeee commented on src/pages/hooks/useScrollY.tsx
> +export default useScrollY;
커스텀훅의 지배자. 커스텀훅의 군림자. 커스텀훅의 권위자. 커스텀훅의 황제. 커스텀훅의 마스터. 커스텀훅의 신. 커스텀훅의 대마왕. 커스텀훅의 정석. 커스텀훅의 달인. 커스텀훅의 대명사...

커스텀훅을 사용해야 할 컴포넌트가 간결해진 것은 말할 필요도 없고, 커스텀훅 내에서 코드도 깔끔하게 잘 정돈되어져 있네요... useEffect 클린업까지 많이 배우고 갑니다!

2024-05-22 02:22 UTC, Ivoryeee commented on src/pages/main/HomePage/components/CarouselWrapperList.tsx
> +const CardWrapper = styled.ul`
진짜 센스왕...

2024-05-22 02:22 UTC, Ivoryeee commented on src/pages/main/HomePage/components/LnbList.tsx
> +  const [isClickIcon, setIsClickIcon] = useState<boolean[]>([false, false, false, false, false, false, false, false]);
우와 이건 저도 배워갑니다!! 이렇게 작성하면 깔끔하게 나타낼 수 있겠네요!! es6 문법 많이 사용하기... 메모

2024-05-22 02:22 UTC, Ivoryeee commented on src/pages/main/HomePage/components/SearchTravel.tsx
> +  }
진짜 인정.

2024-05-22 06:45 UTC, rtttr1 commented on src/assets/images/index.ts
> +export { default as spainImg } from './spain.png';
앗 요거 png 파일이라서 소문자로 해줬는데 png 파일도 컴포넌트화 시켜주는건가요?

2024-05-22 06:46 UTC, rtttr1 commented on src/assets/svgs/index.tsx
> +export { default as searchMiniWhiteIcon } from './ic_search_mini_white_12.svg?react';
얘는 대문자로 해줘야겠네요!

2024-05-22 06:48 UTC, rtttr1 commented on src/components/commons/Header.tsx
> +};
앗 요 컨벤션이 있는걸 늦게 깨달아서 고치고 올려야지! 했는데 까먹고 안고치고 올렸네요... 핳 다고쳐놓겠습니다!!

2024-05-22 06:52 UTC, rtttr1 commented on src/pages/main/HomePage/components/LnbList.tsx
> +  const [isClickIcon, setIsClickIcon] = useState<boolean[]>([false, false, false, false, false, false, false, false]);
오 저는 이런 부분 원래 Array.from({length: 8}, ()=>false) 이렇게 짜는데 Array.fill을 사용하는게 더 간결하네요! 배워갑니다!!!!

2024-05-22 06:58 UTC, rtttr1 commented on src/pages/main/HomePage/components/LnbList.tsx
> +  };
확실히 switch문이 더 가독성이 좋아지네요!!!

2024-05-22 07:06 UTC, rtttr1 commented on src/components/commons/NavHeaderContent.tsx
> +  z-index: 100;
앗 저는 보통 첫 z-index를 100으로 줘서 혹시 나중에 z-index가 더 낮은 컴포넌트를 추가하면 10 이나 1을 줄 수 있게끔 하는 습관?? 을 가지고 있긴 합니닷..!

2024-05-22 07:07 UTC, rtttr1 commented on src/pages/hooks/useScrollY.tsx
> +export default useScrollY;
상아야 이런 주접 어디서 배워왔니...ㅋㅋㅋㅋㅋㅋㅋㅋ 고맙습니다들!!

2024-05-22 07:08 UTC, rtttr1 commented on src/pages/main/HomePage/HomePage.tsx
> +  width: 136.6rem;
앗 알겠습니다!!! 반응형 안할거라서 px을 써야되는군요!

2024-05-22 07:08 UTC, rtttr1 commented on src/pages/main/HomePage/components/CarouselWrapperList.tsx
> +  /* stylelint-disable-next-line unit-allowed-list */
대박 상아짱!!

2024-05-22 07:11 UTC, rtttr1 commented on src/pages/main/HomePage/components/HomeFooter.tsx
> +        })}
앗 그렇네요???? 저는 한줄 이상 넘어가면 return을 써야된다고만 생각해서 return 써줬는데 이친구는 그냥 한줄의 코드로 인식되니까 return 안써줘도 되겠네요 배워갑니다!!!!

2024-05-22 07:12 UTC, rtttr1 commented on src/pages/main/HomePage/constants/index.ts
> +  svgGray: string;
넵넵!!!

2024-05-22 07:13 UTC, rtttr1 commented on src/components/commons/NavHeaderContent.tsx
>  const NavHeaderWrapper = styled.div`
맞아요 이거 안해두니까 다 에러뜨드라구요!!! 한군데만 해두고 다른데를 안해놔서 다 적용시키겠습니다!

2024-05-22 11:25 UTC, jeeminyi commented on src/pages/main/HomePage/components/LnbList.tsx
> +  const [isClickIcon, setIsClickIcon] = useState<boolean[]>([false, false, false, false, false, false, false, false]);
오,,, 이렇게 하면 조금 더 컴팩트하게 작성할 수 있겠군요,,, 하나 배우고 갑니다

2024-05-22 11:26 UTC, jeeminyi commented on src/pages/main/HomePage/components/SearchTravel.tsx
> +  }
저는 마침 캘린더 커스텀 시에 css를 활용해야 해서 어떻게 잘 나눠 쓸 수 있을까 고민하고 있었는데요,,, 배우고 갑니다 👍

2024-05-22 12:42 UTC, jeeminyi approved these changes
커스텀 훅 너무 깔끔하게 잘 해주셨네요,, pr을 꼼꼼하게 잘 작성해주셔서 저에게는 다소 어려운 로직임에도 어떤 고민과 흐름으로 코드를 짜셨는지 이해할 수 있었습니다,,! 고생 많으셨습니다! 우리조 정말 든든국밥이다,,👍

2024-05-23 09:23 UTC, se0jinYoon approved these changes
화긴!!

2024-05-23 09:23 UTC, se0jinYoon commented on src/assets/images/index.ts
> +export { default as spainImg } from './spain.png';
어억 아니요 svg인 줄 알앗어요 냅둬도 됨!!!

2024-05-23 09:44 UTC, merged